// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rt_imp_resizeNNBilinear_9_480_640_1_600_1000_1_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_mat_44_dout,
        in_mat_44_empty_n,
        in_mat_44_read,
        resized_mat_45_din,
        resized_mat_45_full_n,
        resized_mat_45_write
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] in_mat_44_dout;
input   in_mat_44_empty_n;
output   in_mat_44_read;
output  [23:0] resized_mat_45_din;
input   resized_mat_45_full_n;
output   resized_mat_45_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_mat_44_read;
reg resized_mat_45_write;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [32:0] grp_xfUDivResize_fu_178_ap_return;
reg   [32:0] Xscale64_reg_806;
wire    ap_CS_fsm_state2;
wire   [32:0] grp_xfUDivResize_fu_186_ap_return;
reg   [32:0] Yscale64_reg_811;
reg   [22:0] rhs_1_reg_816;
reg   [21:0] conv_i_i_i322_i_cast_reg_821;
wire   [73:0] inscale_V_cast_fu_269_p1;
reg   [73:0] inscale_V_cast_reg_826;
wire    ap_CS_fsm_state3;
wire   [42:0] rhs_fu_272_p1;
reg   [42:0] rhs_reg_831;
wire   [21:0] sub_ln902_fu_275_p2;
reg   [21:0] sub_ln902_reg_836;
reg   [8:0] indexy_V_3_reg_847;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln381_fu_283_p2;
reg   [11:0] Wy_V_reg_853;
wire   [16:0] ret_V_39_fu_499_p3;
reg   [16:0] ret_V_39_reg_859;
wire   [0:0] cmp89_fu_527_p2;
reg   [0:0] cmp89_reg_877;
wire    ap_CS_fsm_state5;
wire   [31:0] op2_assign_fu_534_p2;
reg   [31:0] op2_assign_reg_885;
wire   [0:0] cmp273_fu_540_p2;
reg   [0:0] cmp273_reg_891;
wire   [0:0] cmp277_fu_545_p2;
reg   [0:0] cmp277_reg_896;
wire   [31:0] op2_assign_4_fu_551_p2;
reg   [31:0] op2_assign_4_reg_901;
wire   [0:0] icmp_ln1064_4_fu_560_p2;
reg   [0:0] icmp_ln1064_4_reg_906;
wire   [0:0] xor_ln1076_fu_594_p2;
reg   [0:0] xor_ln1076_reg_911;
wire   [0:0] and_ln485_fu_601_p2;
reg   [0:0] and_ln485_reg_916;
reg   [9:0] line_buffer_V_address0;
reg    line_buffer_V_ce0;
reg    line_buffer_V_we0;
reg   [23:0] line_buffer_V_d0;
wire   [23:0] line_buffer_V_q0;
reg    line_buffer_V_ce1;
wire   [23:0] line_buffer_V_q1;
reg   [9:0] line_buffer_V_1_address0;
reg    line_buffer_V_1_ce0;
reg    line_buffer_V_1_we0;
reg   [23:0] line_buffer_V_1_d0;
wire   [23:0] line_buffer_V_1_q0;
reg    line_buffer_V_1_ce1;
wire   [23:0] line_buffer_V_1_q1;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_done;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_idle;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_ready;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_in_mat_44_read;
wire   [9:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_address0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_ce0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_we0;
wire   [23:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_d0;
wire   [9:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_address0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_ce0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_we0;
wire   [23:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_d0;
wire    grp_xfUDivResize_fu_178_ap_start;
wire    grp_xfUDivResize_fu_178_ap_done;
wire    grp_xfUDivResize_fu_178_ap_idle;
wire    grp_xfUDivResize_fu_178_ap_ready;
wire    grp_xfUDivResize_fu_186_ap_start;
wire    grp_xfUDivResize_fu_186_ap_done;
wire    grp_xfUDivResize_fu_186_ap_idle;
wire    grp_xfUDivResize_fu_186_ap_ready;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_done;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_idle;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_ready;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_in_mat_44_read;
wire   [23:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_resized_mat_45_din;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_resized_mat_45_write;
wire   [9:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_address0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_ce0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_we0;
wire   [23:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_d0;
wire   [9:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_address1;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_ce1;
wire   [9:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_address0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_ce0;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_we0;
wire   [23:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_d0;
wire   [9:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_address1;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_ce1;
wire   [23:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_read_pixel_1_out_o;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_read_pixel_1_out_o_ap_vld;
wire   [16:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_indexy_V_1_out;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_indexy_V_1_out_ap_vld;
wire   [16:0] grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_nextYScale_V_1_out;
wire    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_nextYScale_V_1_out_ap_vld;
reg    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start_reg;
reg    grp_xfUDivResize_fu_178_ap_start_reg;
reg    grp_xfUDivResize_fu_186_ap_start_reg;
reg    grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [23:0] read_pixel_fu_124;
reg   [31:0] read_rows_count_fu_128;
wire   [31:0] read_rows_count_2_fu_702_p3;
wire    ap_CS_fsm_state7;
reg   [31:0] tmp_fu_132;
wire   [31:0] output_rows_count_fu_651_p3;
reg   [31:0] first_row_index_1_fu_136;
wire   [31:0] first_row_index_4_fu_715_p3;
reg   [9:0] i_fu_140;
wire   [9:0] i_2_fu_289_p2;
reg   [16:0] nextYScale_V_fu_144;
reg   [16:0] indexy_V_fu_148;
wire   [19:0] trunc_ln737_fu_298_p1;
wire   [41:0] lhs_fu_302_p3;
wire  signed [41:0] ret_V_40_fu_310_p2;
wire   [32:0] r_V_12_fu_320_p1;
wire   [73:0] r_V_12_fu_320_p2;
wire   [73:0] ret_V_fu_325_p2;
wire  signed [41:0] indexy_pre_comp_V_fu_331_p4;
wire  signed [42:0] lhs_2_fu_361_p1;
wire   [42:0] ret_V_38_fu_365_p2;
wire   [16:0] ret_V_22_cast_fu_370_p4;
wire   [0:0] tmp_36_fu_408_p3;
wire   [0:0] tmp_35_fu_388_p3;
wire   [0:0] cmp_i_i235_i_fu_402_p2;
wire   [0:0] empty_113_fu_424_p2;
wire   [30:0] p_cast40_cast_cast_fu_416_p3;
wire   [30:0] trunc_ln_fu_341_p4;
wire   [30:0] indexy_pre_V_fu_430_p3;
wire   [1:0] tmp_s_fu_452_p4;
wire   [23:0] trunc_ln388_fu_438_p1;
wire   [23:0] rhs_2_fu_462_p3;
wire   [23:0] sub_ln1246_fu_470_p2;
wire   [21:0] trunc_ln379_1_fu_351_p4;
wire   [0:0] icmp_ln902_fu_486_p2;
wire   [16:0] add_i_i_i_i_i286_i_fu_396_p2;
wire   [0:0] tmp_34_fu_380_p3;
wire   [16:0] select_ln901_fu_491_p3;
wire   [31:0] zext_ln1064_1_fu_557_p1;
wire   [0:0] and_ln486_fu_567_p2;
wire   [0:0] icmp_ln1064_5_fu_573_p2;
wire   [31:0] zext_ln1076_1_fu_585_p1;
wire   [0:0] icmp_ln1076_2_fu_588_p2;
wire   [0:0] or_ln485_fu_579_p2;
wire   [31:0] zext_ln1064_fu_614_p1;
wire   [0:0] icmp_ln1064_fu_618_p2;
wire   [0:0] and_ln508_fu_623_p2;
wire   [0:0] icmp_ln1064_3_fu_628_p2;
wire   [0:0] or_ln508_fu_633_p2;
wire   [31:0] add_ln510_fu_639_p2;
wire   [31:0] select_ln508_fu_644_p3;
wire   [31:0] zext_ln1076_fu_657_p1;
wire   [31:0] first_row_index_fu_666_p2;
wire   [0:0] icmp_ln521_fu_671_p2;
wire   [31:0] read_rows_count_1_fu_685_p2;
wire   [0:0] icmp_ln1076_fu_661_p2;
wire   [0:0] and_ln1076_fu_697_p2;
wire   [31:0] sel_tmp1_fu_690_p3;
wire   [31:0] first_row_index_2_fu_677_p3;
wire   [31:0] first_row_index_3_fu_709_p3;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start_reg = 1'b0;
#0 grp_xfUDivResize_fu_178_ap_start_reg = 1'b0;
#0 grp_xfUDivResize_fu_186_ap_start_reg = 1'b0;
#0 grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start_reg = 1'b0;
end

rt_imp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_line_buffbkb #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_V_address0),
    .ce0(line_buffer_V_ce0),
    .we0(line_buffer_V_we0),
    .d0(line_buffer_V_d0),
    .q0(line_buffer_V_q0),
    .address1(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_address1),
    .ce1(line_buffer_V_ce1),
    .q1(line_buffer_V_q1)
);

rt_imp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_line_buffbkb #(
    .DataWidth( 24 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_V_1_address0),
    .ce0(line_buffer_V_1_ce0),
    .we0(line_buffer_V_1_we0),
    .d0(line_buffer_V_1_d0),
    .q0(line_buffer_V_1_q0),
    .address1(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_address1),
    .ce1(line_buffer_V_1_ce1),
    .q1(line_buffer_V_1_q1)
);

rt_imp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2 grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start),
    .ap_done(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_done),
    .ap_idle(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_idle),
    .ap_ready(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_ready),
    .in_mat_44_dout(in_mat_44_dout),
    .in_mat_44_empty_n(in_mat_44_empty_n),
    .in_mat_44_read(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_in_mat_44_read),
    .line_buffer_V_address0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_address0),
    .line_buffer_V_ce0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_ce0),
    .line_buffer_V_we0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_we0),
    .line_buffer_V_d0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_d0),
    .line_buffer_V_1_address0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_address0),
    .line_buffer_V_1_ce0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_ce0),
    .line_buffer_V_1_we0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_we0),
    .line_buffer_V_1_d0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_d0)
);

rt_imp_xfUDivResize grp_xfUDivResize_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfUDivResize_fu_178_ap_start),
    .ap_done(grp_xfUDivResize_fu_178_ap_done),
    .ap_idle(grp_xfUDivResize_fu_178_ap_idle),
    .ap_ready(grp_xfUDivResize_fu_178_ap_ready),
    .in_n(42'd2748779069440),
    .in_d(10'd1000),
    .ap_return(grp_xfUDivResize_fu_178_ap_return)
);

rt_imp_xfUDivResize grp_xfUDivResize_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfUDivResize_fu_186_ap_start),
    .ap_done(grp_xfUDivResize_fu_186_ap_done),
    .ap_idle(grp_xfUDivResize_fu_186_ap_idle),
    .ap_ready(grp_xfUDivResize_fu_186_ap_ready),
    .in_n(42'd2061584302080),
    .in_d(10'd600),
    .ap_return(grp_xfUDivResize_fu_186_ap_return)
);

rt_imp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5 grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start),
    .ap_done(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_done),
    .ap_idle(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_idle),
    .ap_ready(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_ready),
    .in_mat_44_dout(in_mat_44_dout),
    .in_mat_44_empty_n(in_mat_44_empty_n),
    .in_mat_44_read(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_in_mat_44_read),
    .resized_mat_45_din(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_resized_mat_45_din),
    .resized_mat_45_full_n(resized_mat_45_full_n),
    .resized_mat_45_write(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_resized_mat_45_write),
    .indexy_V(indexy_V_fu_148),
    .zext_ln399(indexy_V_3_reg_847),
    .nextYScale_V(nextYScale_V_fu_144),
    .ret_V_39(ret_V_39_reg_859),
    .and_ln485(and_ln485_reg_916),
    .line_buffer_V_address0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_address0),
    .line_buffer_V_ce0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_ce0),
    .line_buffer_V_we0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_we0),
    .line_buffer_V_d0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_d0),
    .line_buffer_V_q0(line_buffer_V_q0),
    .line_buffer_V_address1(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_address1),
    .line_buffer_V_ce1(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_ce1),
    .line_buffer_V_q1(line_buffer_V_q1),
    .line_buffer_V_1_address0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_address0),
    .line_buffer_V_1_ce0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_ce0),
    .line_buffer_V_1_we0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_we0),
    .line_buffer_V_1_d0(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_d0),
    .line_buffer_V_1_q0(line_buffer_V_1_q0),
    .line_buffer_V_1_address1(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_address1),
    .line_buffer_V_1_ce1(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_ce1),
    .line_buffer_V_1_q1(line_buffer_V_1_q1),
    .first_row_index_5(first_row_index_1_fu_136),
    .Xscale64_cast11(Xscale64_reg_806),
    .cmp89(cmp89_reg_877),
    .icmp_ln1076_2(xor_ln1076_reg_911),
    .icmp_ln1064_4(icmp_ln1064_4_reg_906),
    .Wy_V_1(Wy_V_reg_853),
    .zext_ln1171(Wy_V_reg_853),
    .read_pixel_1_out_i(read_pixel_fu_124),
    .read_pixel_1_out_o(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_read_pixel_1_out_o),
    .read_pixel_1_out_o_ap_vld(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_read_pixel_1_out_o_ap_vld),
    .indexy_V_1_out(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_indexy_V_1_out),
    .indexy_V_1_out_ap_vld(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_indexy_V_1_out_ap_vld),
    .nextYScale_V_1_out(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_nextYScale_V_1_out),
    .nextYScale_V_1_out_ap_vld(grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_nextYScale_V_1_out_ap_vld)
);

rt_imp_mul_42s_33ns_74_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 42 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 74 ))
mul_42s_33ns_74_1_1_U98(
    .din0(ret_V_40_fu_310_p2),
    .din1(r_V_12_fu_320_p1),
    .dout(r_V_12_fu_320_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_ready == 1'b1)) begin
            grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start_reg <= 1'b1;
        end else if ((grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_ready == 1'b1)) begin
            grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfUDivResize_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_xfUDivResize_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_xfUDivResize_fu_178_ap_ready == 1'b1)) begin
            grp_xfUDivResize_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfUDivResize_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_xfUDivResize_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_xfUDivResize_fu_186_ap_ready == 1'b1)) begin
            grp_xfUDivResize_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        first_row_index_1_fu_136 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        first_row_index_1_fu_136 <= first_row_index_4_fu_715_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_140 <= 10'd0;
    end else if (((icmp_ln381_fu_283_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_140 <= i_2_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indexy_V_fu_148 <= 17'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        indexy_V_fu_148 <= grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_indexy_V_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        nextYScale_V_fu_144 <= 17'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        nextYScale_V_fu_144 <= grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_nextYScale_V_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        read_rows_count_fu_128 <= 32'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        read_rows_count_fu_128 <= read_rows_count_2_fu_702_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_fu_132 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_fu_132 <= output_rows_count_fu_651_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln381_fu_283_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        Wy_V_reg_853 <= {{sub_ln1246_fu_470_p2[23:12]}};
        indexy_V_3_reg_847 <= {{indexy_pre_V_fu_430_p3[30:22]}};
        ret_V_39_reg_859 <= ret_V_39_fu_499_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Xscale64_reg_806 <= grp_xfUDivResize_fu_178_ap_return;
        Yscale64_reg_811 <= grp_xfUDivResize_fu_186_ap_return;
        conv_i_i_i322_i_cast_reg_821 <= {{grp_xfUDivResize_fu_186_ap_return[31:10]}};
        rhs_1_reg_816 <= {{grp_xfUDivResize_fu_186_ap_return[32:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln485_reg_916 <= and_ln485_fu_601_p2;
        cmp273_reg_891 <= cmp273_fu_540_p2;
        cmp277_reg_896 <= cmp277_fu_545_p2;
        cmp89_reg_877 <= cmp89_fu_527_p2;
        icmp_ln1064_4_reg_906 <= icmp_ln1064_4_fu_560_p2;
        op2_assign_4_reg_901 <= op2_assign_4_fu_551_p2;
        op2_assign_reg_885 <= op2_assign_fu_534_p2;
        xor_ln1076_reg_911 <= xor_ln1076_fu_594_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        inscale_V_cast_reg_826[32 : 0] <= inscale_V_cast_fu_269_p1[32 : 0];
        rhs_reg_831[22 : 0] <= rhs_fu_272_p1[22 : 0];
        sub_ln902_reg_836 <= sub_ln902_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_read_pixel_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        read_pixel_fu_124 <= grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_read_pixel_1_out_o;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln381_fu_283_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln381_fu_283_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_mat_44_read = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_in_mat_44_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_mat_44_read = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_in_mat_44_read;
    end else begin
        in_mat_44_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_1_address0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_1_address0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_address0;
    end else begin
        line_buffer_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_1_ce0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_1_ce0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_ce0;
    end else begin
        line_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_1_ce1 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_ce1;
    end else begin
        line_buffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_1_d0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_1_d0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_d0;
    end else begin
        line_buffer_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_1_we0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_1_we0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_1_we0;
    end else begin
        line_buffer_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_address0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_address0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_address0;
    end else begin
        line_buffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_ce0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_ce0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_ce0;
    end else begin
        line_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_ce1 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_ce1;
    end else begin
        line_buffer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_d0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_d0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_d0;
    end else begin
        line_buffer_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        line_buffer_V_we0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_line_buffer_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        line_buffer_V_we0 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_line_buffer_V_we0;
    end else begin
        line_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        resized_mat_45_write = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_resized_mat_45_write;
    end else begin
        resized_mat_45_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln381_fu_283_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i_i_i_i_i286_i_fu_396_p2 = (ret_V_22_cast_fu_370_p4 + 17'd1);

assign add_ln510_fu_639_p2 = (tmp_fu_132 + 32'd1);

assign and_ln1076_fu_697_p2 = (icmp_ln1076_fu_661_p2 & cmp89_reg_877);

assign and_ln485_fu_601_p2 = (or_ln485_fu_579_p2 & cmp273_fu_540_p2);

assign and_ln486_fu_567_p2 = (icmp_ln1064_4_fu_560_p2 & cmp277_fu_545_p2);

assign and_ln508_fu_623_p2 = (icmp_ln1064_fu_618_p2 & cmp277_reg_896);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_xfUDivResize_fu_186_ap_done == 1'b0) | (grp_xfUDivResize_fu_178_ap_done == 1'b0) | (grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_done == 1'b0));
end

assign cmp273_fu_540_p2 = (($signed(tmp_fu_132) < $signed(32'd600)) ? 1'b1 : 1'b0);

assign cmp277_fu_545_p2 = ((read_rows_count_fu_128 == 32'd480) ? 1'b1 : 1'b0);

assign cmp89_fu_527_p2 = ((read_rows_count_fu_128 != 32'd480) ? 1'b1 : 1'b0);

assign cmp_i_i235_i_fu_402_p2 = (($signed(indexy_pre_comp_V_fu_331_p4) > $signed(42'd2009071616)) ? 1'b1 : 1'b0);

assign empty_113_fu_424_p2 = (tmp_35_fu_388_p3 | cmp_i_i235_i_fu_402_p2);

assign first_row_index_2_fu_677_p3 = ((icmp_ln521_fu_671_p2[0:0] == 1'b1) ? 32'd0 : first_row_index_fu_666_p2);

assign first_row_index_3_fu_709_p3 = ((cmp89_reg_877[0:0] == 1'b1) ? first_row_index_2_fu_677_p3 : first_row_index_1_fu_136);

assign first_row_index_4_fu_715_p3 = ((and_ln1076_fu_697_p2[0:0] == 1'b1) ? first_row_index_1_fu_136 : first_row_index_3_fu_709_p3);

assign first_row_index_fu_666_p2 = (first_row_index_1_fu_136 + 32'd1);

assign grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_331_1_VITIS_LOOP_336_2_fu_168_ap_start_reg;

assign grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_ap_start_reg;

assign grp_xfUDivResize_fu_178_ap_start = grp_xfUDivResize_fu_178_ap_start_reg;

assign grp_xfUDivResize_fu_186_ap_start = grp_xfUDivResize_fu_186_ap_start_reg;

assign i_2_fu_289_p2 = (i_fu_140 + 10'd1);

assign icmp_ln1064_3_fu_628_p2 = ((zext_ln1064_fu_614_p1 == op2_assign_4_reg_901) ? 1'b1 : 1'b0);

assign icmp_ln1064_4_fu_560_p2 = ((zext_ln1064_1_fu_557_p1 == op2_assign_fu_534_p2) ? 1'b1 : 1'b0);

assign icmp_ln1064_5_fu_573_p2 = ((zext_ln1064_1_fu_557_p1 == op2_assign_4_fu_551_p2) ? 1'b1 : 1'b0);

assign icmp_ln1064_fu_618_p2 = ((zext_ln1064_fu_614_p1 == op2_assign_reg_885) ? 1'b1 : 1'b0);

assign icmp_ln1076_2_fu_588_p2 = (($signed(zext_ln1076_1_fu_585_p1) < $signed(op2_assign_fu_534_p2)) ? 1'b1 : 1'b0);

assign icmp_ln1076_fu_661_p2 = (($signed(zext_ln1076_fu_657_p1) < $signed(op2_assign_reg_885)) ? 1'b1 : 1'b0);

assign icmp_ln381_fu_283_p2 = ((i_fu_140 == 10'd600) ? 1'b1 : 1'b0);

assign icmp_ln521_fu_671_p2 = ((first_row_index_fu_666_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln902_fu_486_p2 = ((trunc_ln379_1_fu_351_p4 != sub_ln902_reg_836) ? 1'b1 : 1'b0);

assign indexy_pre_V_fu_430_p3 = ((empty_113_fu_424_p2[0:0] == 1'b1) ? p_cast40_cast_cast_fu_416_p3 : trunc_ln_fu_341_p4);

assign indexy_pre_comp_V_fu_331_p4 = {{ret_V_fu_325_p2[73:32]}};

assign inscale_V_cast_fu_269_p1 = Yscale64_reg_811;

assign lhs_2_fu_361_p1 = indexy_pre_comp_V_fu_331_p4;

assign lhs_fu_302_p3 = {{trunc_ln737_fu_298_p1}, {22'd0}};

assign op2_assign_4_fu_551_p2 = ($signed(read_rows_count_fu_128) + $signed(32'd4294967294));

assign op2_assign_fu_534_p2 = ($signed(read_rows_count_fu_128) + $signed(32'd4294967295));

assign or_ln485_fu_579_p2 = (icmp_ln1064_5_fu_573_p2 | and_ln486_fu_567_p2);

assign or_ln508_fu_633_p2 = (icmp_ln1064_3_fu_628_p2 | and_ln508_fu_623_p2);

assign output_rows_count_fu_651_p3 = ((cmp273_reg_891[0:0] == 1'b1) ? select_ln508_fu_644_p3 : tmp_fu_132);

assign p_cast40_cast_cast_fu_416_p3 = ((tmp_36_fu_408_p3[0:0] == 1'b1) ? 31'd0 : 31'd2009071616);

assign r_V_12_fu_320_p1 = inscale_V_cast_reg_826;

assign read_rows_count_1_fu_685_p2 = (read_rows_count_fu_128 + 32'd1);

assign read_rows_count_2_fu_702_p3 = ((and_ln1076_fu_697_p2[0:0] == 1'b1) ? read_rows_count_fu_128 : sel_tmp1_fu_690_p3);

assign resized_mat_45_din = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_resized_mat_45_din;

assign ret_V_22_cast_fu_370_p4 = {{ret_V_38_fu_365_p2[38:22]}};

assign ret_V_38_fu_365_p2 = ($signed(lhs_2_fu_361_p1) + $signed(rhs_reg_831));

assign ret_V_39_fu_499_p3 = ((tmp_34_fu_380_p3[0:0] == 1'b1) ? select_ln901_fu_491_p3 : ret_V_22_cast_fu_370_p4);

assign ret_V_40_fu_310_p2 = (lhs_fu_302_p3 | 42'd2097152);

assign ret_V_fu_325_p2 = ($signed(r_V_12_fu_320_p2) + $signed(74'd18889456924279326113792));

assign rhs_2_fu_462_p3 = {{tmp_s_fu_452_p4}, {22'd0}};

assign rhs_fu_272_p1 = rhs_1_reg_816;

assign sel_tmp1_fu_690_p3 = ((cmp89_reg_877[0:0] == 1'b1) ? read_rows_count_1_fu_685_p2 : 32'd480);

assign select_ln508_fu_644_p3 = ((or_ln508_fu_633_p2[0:0] == 1'b1) ? add_ln510_fu_639_p2 : tmp_fu_132);

assign select_ln901_fu_491_p3 = ((icmp_ln902_fu_486_p2[0:0] == 1'b1) ? add_i_i_i_i_i286_i_fu_396_p2 : ret_V_22_cast_fu_370_p4);

assign sub_ln1246_fu_470_p2 = (trunc_ln388_fu_438_p1 - rhs_2_fu_462_p3);

assign sub_ln902_fu_275_p2 = (22'd0 - conv_i_i_i322_i_cast_reg_821);

assign tmp_34_fu_380_p3 = ret_V_38_fu_365_p2[32'd42];

assign tmp_35_fu_388_p3 = ret_V_fu_325_p2[32'd73];

assign tmp_36_fu_408_p3 = ret_V_fu_325_p2[32'd73];

assign tmp_s_fu_452_p4 = {{indexy_pre_V_fu_430_p3[23:22]}};

assign trunc_ln379_1_fu_351_p4 = {{ret_V_fu_325_p2[53:32]}};

assign trunc_ln388_fu_438_p1 = indexy_pre_V_fu_430_p3[23:0];

assign trunc_ln737_fu_298_p1 = tmp_fu_132[19:0];

assign trunc_ln_fu_341_p4 = {{ret_V_fu_325_p2[62:32]}};

assign xor_ln1076_fu_594_p2 = (icmp_ln1076_2_fu_588_p2 ^ 1'd1);

assign zext_ln1064_1_fu_557_p1 = indexy_V_3_reg_847;

assign zext_ln1064_fu_614_p1 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_indexy_V_1_out;

assign zext_ln1076_1_fu_585_p1 = ret_V_39_reg_859;

assign zext_ln1076_fu_657_p1 = grp_resizeNNBilinear_9_480_640_1_600_1000_1_2_Pipeline_VITIS_LOOP_388_5_fu_194_nextYScale_V_1_out;

always @ (posedge ap_clk) begin
    inscale_V_cast_reg_826[73:33] <= 41'b00000000000000000000000000000000000000000;
    rhs_reg_831[42:23] <= 20'b00000000000000000000;
end

endmodule //rt_imp_resizeNNBilinear_9_480_640_1_600_1000_1_2_s
