// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rt_imp_rt_imp_Pipeline_VITIS_LOOP_218_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        memif_hwt2mem_din,
        memif_hwt2mem_full_n,
        memif_hwt2mem_write,
        p_i,
        p_addr_7,
        p_rem_11,
        zext_ln218_2,
        ram_out_V_address0,
        ram_out_V_ce0,
        ram_out_V_q0,
        p_i_1_out,
        p_i_1_out_ap_vld,
        p_addr_10_out,
        p_addr_10_out_ap_vld,
        p_rem_6_out,
        p_rem_6_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [63:0] memif_hwt2mem_din;
input   memif_hwt2mem_full_n;
output   memif_hwt2mem_write;
input  [63:0] p_i;
input  [63:0] p_addr_7;
input  [63:0] p_rem_11;
input  [8:0] zext_ln218_2;
output  [16:0] ram_out_V_address0;
output   ram_out_V_ce0;
input  [63:0] ram_out_V_q0;
output  [63:0] p_i_1_out;
output   p_i_1_out_ap_vld;
output  [63:0] p_addr_10_out;
output   p_addr_10_out_ap_vld;
output  [63:0] p_rem_6_out;
output   p_rem_6_out_ap_vld;

reg ap_idle;
reg memif_hwt2mem_write;
reg ram_out_V_ce0;
reg p_i_1_out_ap_vld;
reg p_addr_10_out_ap_vld;
reg p_rem_6_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln218_fu_161_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    memif_hwt2mem_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] p_len_fu_52;
wire   [63:0] p_len_2_fu_195_p2;
wire   [63:0] zext_ln218_2_cast_fu_134_p1;
wire    ap_loop_init;
reg   [63:0] p_rem_fu_56;
wire   [63:0] p_rem_1_fu_189_p2;
reg   [63:0] p_addr_fu_60;
wire   [63:0] p_addr_1_fu_183_p2;
reg   [63:0] p_i_1_fu_64;
wire   [63:0] p_i_2_fu_177_p2;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

rt_imp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_addr_fu_60 <= p_addr_7;
        end else if (((icmp_ln218_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_addr_fu_60 <= p_addr_1_fu_183_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_i_1_fu_64 <= p_i;
        end else if (((icmp_ln218_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_i_1_fu_64 <= p_i_2_fu_177_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_len_fu_52 <= zext_ln218_2_cast_fu_134_p1;
        end else if (((icmp_ln218_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_len_fu_52 <= p_len_2_fu_195_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_rem_fu_56 <= p_rem_11;
        end else if (((icmp_ln218_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_rem_fu_56 <= p_rem_1_fu_189_p2;
        end
    end
end

always @ (*) begin
    if (((icmp_ln218_fu_161_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        memif_hwt2mem_blk_n = memif_hwt2mem_full_n;
    end else begin
        memif_hwt2mem_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        memif_hwt2mem_write = 1'b1;
    end else begin
        memif_hwt2mem_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln218_fu_161_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_addr_10_out_ap_vld = 1'b1;
    end else begin
        p_addr_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln218_fu_161_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_i_1_out_ap_vld = 1'b1;
    end else begin
        p_i_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln218_fu_161_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_rem_6_out_ap_vld = 1'b1;
    end else begin
        p_rem_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ram_out_V_ce0 = 1'b1;
    end else begin
        ram_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((memif_hwt2mem_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((memif_hwt2mem_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((memif_hwt2mem_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (memif_hwt2mem_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln218_fu_161_p2 = ((p_len_fu_52 == 64'd0) ? 1'b1 : 1'b0);

assign memif_hwt2mem_din = ram_out_V_q0;

assign p_addr_10_out = p_addr_fu_60;

assign p_addr_1_fu_183_p2 = (p_addr_fu_60 + 64'd8);

assign p_i_1_out = p_i_1_fu_64;

assign p_i_2_fu_177_p2 = (p_i_1_fu_64 + 64'd1);

assign p_len_2_fu_195_p2 = ($signed(p_len_fu_52) + $signed(64'd18446744073709551608));

assign p_rem_1_fu_189_p2 = ($signed(p_rem_fu_56) + $signed(64'd18446744073709551608));

assign p_rem_6_out = p_rem_fu_56;

assign ram_out_V_address0 = p_i_1_fu_64;

assign zext_ln218_2_cast_fu_134_p1 = zext_ln218_2;

endmodule //rt_imp_rt_imp_Pipeline_VITIS_LOOP_218_7
