-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rt_imp_proc is
port (
    memif_hwt2mem_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    memif_hwt2mem_full_n : IN STD_LOGIC;
    memif_hwt2mem_write : OUT STD_LOGIC;
    memif_mem2hwt_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    memif_mem2hwt_empty_n : IN STD_LOGIC;
    memif_mem2hwt_read : OUT STD_LOGIC;
    pMessage : IN STD_LOGIC_VECTOR (63 downto 0);
    ram_out_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ram_out_ce0 : OUT STD_LOGIC;
    ram_out_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ram_out_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    ram_out_we0 : OUT STD_LOGIC;
    ram_out_address1 : OUT STD_LOGIC_VECTOR (16 downto 0);
    ram_out_ce1 : OUT STD_LOGIC;
    ram_out_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    ram_out_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    ram_out_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    pMessage_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of rt_imp_proc is 
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';

attribute shreg_extract : string;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_start : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_done : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_continue : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_idle : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_ready : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_start_out : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_start_write : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_mem2hwt_read : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_ram_in_V_din : STD_LOGIC_VECTOR (63 downto 0);
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_ram_in_V_write : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_hwt2mem_din : STD_LOGIC_VECTOR (63 downto 0);
    signal proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_hwt2mem_write : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_ap_start : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_ap_done : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_ap_continue : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_ap_idle : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_ap_ready : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_in_mat_data_din : STD_LOGIC_VECTOR (23 downto 0);
    signal proc_Loop_loop_read_proc6_U0_in_mat_data_write : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_start_out : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_start_write : STD_LOGIC;
    signal proc_Loop_loop_read_proc6_U0_ram_in_V_read : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_ap_start : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_ap_done : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_ap_continue : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_ap_idle : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_ap_ready : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_start_out : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_start_write : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_in_mat_44_read : STD_LOGIC;
    signal resize_1_9_480_640_600_1000_1_2_U0_resized_mat_45_din : STD_LOGIC_VECTOR (23 downto 0);
    signal resize_1_9_480_640_600_1000_1_2_U0_resized_mat_45_write : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_start : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_done : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_continue : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_idle : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_ready : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_resized_mat_data_read : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_tmp_mat_data_din : STD_LOGIC_VECTOR (31 downto 0);
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_tmp_mat_data_write : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_start_out : STD_LOGIC;
    signal proc_Loop_VITIS_LOOP_132_3_proc7_U0_start_write : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_start : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_done : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_continue : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_idle : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_ready : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_start_out : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_start_write : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_tmp_mat_46_read : STD_LOGIC;
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_out_mat_47_din : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransform_100_50_0_true_7_600_1000_1_false_U0_out_mat_47_write : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ap_start : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ap_done : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ap_continue : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ap_idle : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ap_ready : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_out_mat_data_read : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ram_out_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal proc_Loop_loop_write_proc8_U0_ram_out_ce0 : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ram_out_we0 : STD_LOGIC;
    signal proc_Loop_loop_write_proc8_U0_ram_out_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal ram_in_V_full_n : STD_LOGIC;
    signal ram_in_V_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal ram_in_V_empty_n : STD_LOGIC;
    signal in_mat_data_full_n : STD_LOGIC;
    signal in_mat_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal in_mat_data_empty_n : STD_LOGIC;
    signal resized_mat_data_full_n : STD_LOGIC;
    signal resized_mat_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal resized_mat_data_empty_n : STD_LOGIC;
    signal tmp_mat_data_full_n : STD_LOGIC;
    signal tmp_mat_data_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_mat_data_empty_n : STD_LOGIC;
    signal out_mat_data_full_n : STD_LOGIC;
    signal out_mat_data_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal out_mat_data_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal start_for_proc_Loop_loop_read_proc6_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_Loop_loop_read_proc6_U0_full_n : STD_LOGIC;
    signal start_for_proc_Loop_loop_read_proc6_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_Loop_loop_read_proc6_U0_empty_n : STD_LOGIC;
    signal start_for_resize_1_9_480_640_600_1000_1_2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_resize_1_9_480_640_600_1000_1_2_U0_full_n : STD_LOGIC;
    signal start_for_resize_1_9_480_640_600_1000_1_2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_resize_1_9_480_640_600_1000_1_2_U0_empty_n : STD_LOGIC;
    signal start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_full_n : STD_LOGIC;
    signal start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_empty_n : STD_LOGIC;
    signal start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_full_n : STD_LOGIC;
    signal start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_empty_n : STD_LOGIC;
    signal start_for_proc_Loop_loop_write_proc8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_Loop_loop_write_proc8_U0_full_n : STD_LOGIC;
    signal start_for_proc_Loop_loop_write_proc8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_Loop_loop_write_proc8_U0_empty_n : STD_LOGIC;

    component rt_imp_proc_Loop_VITIS_LOOP_78_1_proc5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        pMessage : IN STD_LOGIC_VECTOR (63 downto 0);
        memif_mem2hwt_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        memif_mem2hwt_empty_n : IN STD_LOGIC;
        memif_mem2hwt_read : OUT STD_LOGIC;
        ram_in_V_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        ram_in_V_full_n : IN STD_LOGIC;
        ram_in_V_write : OUT STD_LOGIC;
        memif_hwt2mem_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        memif_hwt2mem_full_n : IN STD_LOGIC;
        memif_hwt2mem_write : OUT STD_LOGIC );
    end component;


    component rt_imp_proc_Loop_loop_read_proc6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_mat_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        in_mat_data_full_n : IN STD_LOGIC;
        in_mat_data_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        ram_in_V_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        ram_in_V_empty_n : IN STD_LOGIC;
        ram_in_V_read : OUT STD_LOGIC );
    end component;


    component rt_imp_resize_1_9_480_640_600_1000_1_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        in_mat_44_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        in_mat_44_empty_n : IN STD_LOGIC;
        in_mat_44_read : OUT STD_LOGIC;
        resized_mat_45_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        resized_mat_45_full_n : IN STD_LOGIC;
        resized_mat_45_write : OUT STD_LOGIC );
    end component;


    component rt_imp_proc_Loop_VITIS_LOOP_132_3_proc7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        resized_mat_data_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        resized_mat_data_empty_n : IN STD_LOGIC;
        resized_mat_data_read : OUT STD_LOGIC;
        tmp_mat_data_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        tmp_mat_data_full_n : IN STD_LOGIC;
        tmp_mat_data_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component rt_imp_warpTransform_100_50_0_true_7_600_1000_1_false_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        tmp_mat_46_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_mat_46_empty_n : IN STD_LOGIC;
        tmp_mat_46_read : OUT STD_LOGIC;
        out_mat_47_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_mat_47_full_n : IN STD_LOGIC;
        out_mat_47_write : OUT STD_LOGIC );
    end component;


    component rt_imp_proc_Loop_loop_write_proc8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_mat_data_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        out_mat_data_empty_n : IN STD_LOGIC;
        out_mat_data_read : OUT STD_LOGIC;
        ram_out_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        ram_out_ce0 : OUT STD_LOGIC;
        ram_out_we0 : OUT STD_LOGIC;
        ram_out_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component rt_imp_fifo_w64_d32_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_fifo_w24_d1000_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_fifo_w32_d1000_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_start_for_proc_Loop_loop_read_proc6_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_start_for_resize_1_9_480_640_600_1000_1_2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_start_for_proc_Loop_loop_write_proc8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    proc_Loop_VITIS_LOOP_78_1_proc5_U0 : component rt_imp_proc_Loop_VITIS_LOOP_78_1_proc5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_start,
        start_full_n => start_for_proc_Loop_loop_read_proc6_U0_full_n,
        ap_done => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_done,
        ap_continue => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_continue,
        ap_idle => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_idle,
        ap_ready => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_ready,
        start_out => proc_Loop_VITIS_LOOP_78_1_proc5_U0_start_out,
        start_write => proc_Loop_VITIS_LOOP_78_1_proc5_U0_start_write,
        pMessage => pMessage,
        memif_mem2hwt_dout => memif_mem2hwt_dout,
        memif_mem2hwt_empty_n => memif_mem2hwt_empty_n,
        memif_mem2hwt_read => proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_mem2hwt_read,
        ram_in_V_din => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ram_in_V_din,
        ram_in_V_full_n => ram_in_V_full_n,
        ram_in_V_write => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ram_in_V_write,
        memif_hwt2mem_din => proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_hwt2mem_din,
        memif_hwt2mem_full_n => memif_hwt2mem_full_n,
        memif_hwt2mem_write => proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_hwt2mem_write);

    proc_Loop_loop_read_proc6_U0 : component rt_imp_proc_Loop_loop_read_proc6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => proc_Loop_loop_read_proc6_U0_ap_start,
        start_full_n => start_for_resize_1_9_480_640_600_1000_1_2_U0_full_n,
        ap_done => proc_Loop_loop_read_proc6_U0_ap_done,
        ap_continue => proc_Loop_loop_read_proc6_U0_ap_continue,
        ap_idle => proc_Loop_loop_read_proc6_U0_ap_idle,
        ap_ready => proc_Loop_loop_read_proc6_U0_ap_ready,
        in_mat_data_din => proc_Loop_loop_read_proc6_U0_in_mat_data_din,
        in_mat_data_full_n => in_mat_data_full_n,
        in_mat_data_write => proc_Loop_loop_read_proc6_U0_in_mat_data_write,
        start_out => proc_Loop_loop_read_proc6_U0_start_out,
        start_write => proc_Loop_loop_read_proc6_U0_start_write,
        ram_in_V_dout => ram_in_V_dout,
        ram_in_V_empty_n => ram_in_V_empty_n,
        ram_in_V_read => proc_Loop_loop_read_proc6_U0_ram_in_V_read);

    resize_1_9_480_640_600_1000_1_2_U0 : component rt_imp_resize_1_9_480_640_600_1000_1_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => resize_1_9_480_640_600_1000_1_2_U0_ap_start,
        start_full_n => start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_full_n,
        ap_done => resize_1_9_480_640_600_1000_1_2_U0_ap_done,
        ap_continue => resize_1_9_480_640_600_1000_1_2_U0_ap_continue,
        ap_idle => resize_1_9_480_640_600_1000_1_2_U0_ap_idle,
        ap_ready => resize_1_9_480_640_600_1000_1_2_U0_ap_ready,
        start_out => resize_1_9_480_640_600_1000_1_2_U0_start_out,
        start_write => resize_1_9_480_640_600_1000_1_2_U0_start_write,
        in_mat_44_dout => in_mat_data_dout,
        in_mat_44_empty_n => in_mat_data_empty_n,
        in_mat_44_read => resize_1_9_480_640_600_1000_1_2_U0_in_mat_44_read,
        resized_mat_45_din => resize_1_9_480_640_600_1000_1_2_U0_resized_mat_45_din,
        resized_mat_45_full_n => resized_mat_data_full_n,
        resized_mat_45_write => resize_1_9_480_640_600_1000_1_2_U0_resized_mat_45_write);

    proc_Loop_VITIS_LOOP_132_3_proc7_U0 : component rt_imp_proc_Loop_VITIS_LOOP_132_3_proc7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_start,
        start_full_n => start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_full_n,
        ap_done => proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_done,
        ap_continue => proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_continue,
        ap_idle => proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_idle,
        ap_ready => proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_ready,
        resized_mat_data_dout => resized_mat_data_dout,
        resized_mat_data_empty_n => resized_mat_data_empty_n,
        resized_mat_data_read => proc_Loop_VITIS_LOOP_132_3_proc7_U0_resized_mat_data_read,
        tmp_mat_data_din => proc_Loop_VITIS_LOOP_132_3_proc7_U0_tmp_mat_data_din,
        tmp_mat_data_full_n => tmp_mat_data_full_n,
        tmp_mat_data_write => proc_Loop_VITIS_LOOP_132_3_proc7_U0_tmp_mat_data_write,
        start_out => proc_Loop_VITIS_LOOP_132_3_proc7_U0_start_out,
        start_write => proc_Loop_VITIS_LOOP_132_3_proc7_U0_start_write);

    warpTransform_100_50_0_true_7_600_1000_1_false_U0 : component rt_imp_warpTransform_100_50_0_true_7_600_1000_1_false_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_start,
        start_full_n => start_for_proc_Loop_loop_write_proc8_U0_full_n,
        ap_done => warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_done,
        ap_continue => warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_continue,
        ap_idle => warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_idle,
        ap_ready => warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_ready,
        start_out => warpTransform_100_50_0_true_7_600_1000_1_false_U0_start_out,
        start_write => warpTransform_100_50_0_true_7_600_1000_1_false_U0_start_write,
        tmp_mat_46_dout => tmp_mat_data_dout,
        tmp_mat_46_empty_n => tmp_mat_data_empty_n,
        tmp_mat_46_read => warpTransform_100_50_0_true_7_600_1000_1_false_U0_tmp_mat_46_read,
        out_mat_47_din => warpTransform_100_50_0_true_7_600_1000_1_false_U0_out_mat_47_din,
        out_mat_47_full_n => out_mat_data_full_n,
        out_mat_47_write => warpTransform_100_50_0_true_7_600_1000_1_false_U0_out_mat_47_write);

    proc_Loop_loop_write_proc8_U0 : component rt_imp_proc_Loop_loop_write_proc8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => proc_Loop_loop_write_proc8_U0_ap_start,
        ap_done => proc_Loop_loop_write_proc8_U0_ap_done,
        ap_continue => proc_Loop_loop_write_proc8_U0_ap_continue,
        ap_idle => proc_Loop_loop_write_proc8_U0_ap_idle,
        ap_ready => proc_Loop_loop_write_proc8_U0_ap_ready,
        out_mat_data_dout => out_mat_data_dout,
        out_mat_data_empty_n => out_mat_data_empty_n,
        out_mat_data_read => proc_Loop_loop_write_proc8_U0_out_mat_data_read,
        ram_out_address0 => proc_Loop_loop_write_proc8_U0_ram_out_address0,
        ram_out_ce0 => proc_Loop_loop_write_proc8_U0_ram_out_ce0,
        ram_out_we0 => proc_Loop_loop_write_proc8_U0_ram_out_we0,
        ram_out_d0 => proc_Loop_loop_write_proc8_U0_ram_out_d0);

    ram_in_V_U : component rt_imp_fifo_w64_d32_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ram_in_V_din,
        if_full_n => ram_in_V_full_n,
        if_write => proc_Loop_VITIS_LOOP_78_1_proc5_U0_ram_in_V_write,
        if_dout => ram_in_V_dout,
        if_empty_n => ram_in_V_empty_n,
        if_read => proc_Loop_loop_read_proc6_U0_ram_in_V_read);

    in_mat_data_U : component rt_imp_fifo_w24_d1000_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => proc_Loop_loop_read_proc6_U0_in_mat_data_din,
        if_full_n => in_mat_data_full_n,
        if_write => proc_Loop_loop_read_proc6_U0_in_mat_data_write,
        if_dout => in_mat_data_dout,
        if_empty_n => in_mat_data_empty_n,
        if_read => resize_1_9_480_640_600_1000_1_2_U0_in_mat_44_read);

    resized_mat_data_U : component rt_imp_fifo_w24_d1000_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => resize_1_9_480_640_600_1000_1_2_U0_resized_mat_45_din,
        if_full_n => resized_mat_data_full_n,
        if_write => resize_1_9_480_640_600_1000_1_2_U0_resized_mat_45_write,
        if_dout => resized_mat_data_dout,
        if_empty_n => resized_mat_data_empty_n,
        if_read => proc_Loop_VITIS_LOOP_132_3_proc7_U0_resized_mat_data_read);

    tmp_mat_data_U : component rt_imp_fifo_w32_d1000_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => proc_Loop_VITIS_LOOP_132_3_proc7_U0_tmp_mat_data_din,
        if_full_n => tmp_mat_data_full_n,
        if_write => proc_Loop_VITIS_LOOP_132_3_proc7_U0_tmp_mat_data_write,
        if_dout => tmp_mat_data_dout,
        if_empty_n => tmp_mat_data_empty_n,
        if_read => warpTransform_100_50_0_true_7_600_1000_1_false_U0_tmp_mat_46_read);

    out_mat_data_U : component rt_imp_fifo_w32_d1000_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransform_100_50_0_true_7_600_1000_1_false_U0_out_mat_47_din,
        if_full_n => out_mat_data_full_n,
        if_write => warpTransform_100_50_0_true_7_600_1000_1_false_U0_out_mat_47_write,
        if_dout => out_mat_data_dout,
        if_empty_n => out_mat_data_empty_n,
        if_read => proc_Loop_loop_write_proc8_U0_out_mat_data_read);

    start_for_proc_Loop_loop_read_proc6_U0_U : component rt_imp_start_for_proc_Loop_loop_read_proc6_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_proc_Loop_loop_read_proc6_U0_din,
        if_full_n => start_for_proc_Loop_loop_read_proc6_U0_full_n,
        if_write => proc_Loop_VITIS_LOOP_78_1_proc5_U0_start_write,
        if_dout => start_for_proc_Loop_loop_read_proc6_U0_dout,
        if_empty_n => start_for_proc_Loop_loop_read_proc6_U0_empty_n,
        if_read => proc_Loop_loop_read_proc6_U0_ap_ready);

    start_for_resize_1_9_480_640_600_1000_1_2_U0_U : component rt_imp_start_for_resize_1_9_480_640_600_1000_1_2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_resize_1_9_480_640_600_1000_1_2_U0_din,
        if_full_n => start_for_resize_1_9_480_640_600_1000_1_2_U0_full_n,
        if_write => proc_Loop_loop_read_proc6_U0_start_write,
        if_dout => start_for_resize_1_9_480_640_600_1000_1_2_U0_dout,
        if_empty_n => start_for_resize_1_9_480_640_600_1000_1_2_U0_empty_n,
        if_read => resize_1_9_480_640_600_1000_1_2_U0_ap_ready);

    start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_U : component rt_imp_start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_din,
        if_full_n => start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_full_n,
        if_write => resize_1_9_480_640_600_1000_1_2_U0_start_write,
        if_dout => start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_dout,
        if_empty_n => start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_empty_n,
        if_read => proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_ready);

    start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_U : component rt_imp_start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_din,
        if_full_n => start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_full_n,
        if_write => proc_Loop_VITIS_LOOP_132_3_proc7_U0_start_write,
        if_dout => start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_dout,
        if_empty_n => start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_empty_n,
        if_read => warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_ready);

    start_for_proc_Loop_loop_write_proc8_U0_U : component rt_imp_start_for_proc_Loop_loop_write_proc8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_proc_Loop_loop_write_proc8_U0_din,
        if_full_n => start_for_proc_Loop_loop_write_proc8_U0_full_n,
        if_write => warpTransform_100_50_0_true_7_600_1000_1_false_U0_start_write,
        if_dout => start_for_proc_Loop_loop_write_proc8_U0_dout,
        if_empty_n => start_for_proc_Loop_loop_write_proc8_U0_empty_n,
        if_read => proc_Loop_loop_write_proc8_U0_ap_ready);




    ap_done <= ap_sync_done;
    ap_idle <= (warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_idle and resize_1_9_480_640_600_1000_1_2_U0_ap_idle and proc_Loop_loop_write_proc8_U0_ap_idle and proc_Loop_loop_read_proc6_U0_ap_idle and proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_idle and proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_idle);
    ap_ready <= proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_ready;
    ap_sync_continue <= (ap_sync_done and ap_continue);
    ap_sync_done <= (proc_Loop_loop_write_proc8_U0_ap_done and proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_done);
    memif_hwt2mem_din <= proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_hwt2mem_din;
    memif_hwt2mem_write <= proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_hwt2mem_write;
    memif_mem2hwt_read <= proc_Loop_VITIS_LOOP_78_1_proc5_U0_memif_mem2hwt_read;
    proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_continue <= ap_const_logic_1;
    proc_Loop_VITIS_LOOP_132_3_proc7_U0_ap_start <= start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_empty_n;
    proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_continue <= ap_sync_continue;
    proc_Loop_VITIS_LOOP_78_1_proc5_U0_ap_start <= ap_start;
    proc_Loop_loop_read_proc6_U0_ap_continue <= ap_const_logic_1;
    proc_Loop_loop_read_proc6_U0_ap_start <= start_for_proc_Loop_loop_read_proc6_U0_empty_n;
    proc_Loop_loop_write_proc8_U0_ap_continue <= ap_sync_continue;
    proc_Loop_loop_write_proc8_U0_ap_start <= start_for_proc_Loop_loop_write_proc8_U0_empty_n;
    ram_out_address0 <= proc_Loop_loop_write_proc8_U0_ram_out_address0;
    ram_out_address1 <= ap_const_lv17_0;
    ram_out_ce0 <= proc_Loop_loop_write_proc8_U0_ram_out_ce0;
    ram_out_ce1 <= ap_const_logic_0;
    ram_out_d0 <= proc_Loop_loop_write_proc8_U0_ram_out_d0;
    ram_out_d1 <= ap_const_lv64_0;
    ram_out_we0 <= proc_Loop_loop_write_proc8_U0_ram_out_we0;
    ram_out_we1 <= ap_const_logic_0;
    resize_1_9_480_640_600_1000_1_2_U0_ap_continue <= ap_const_logic_1;
    resize_1_9_480_640_600_1000_1_2_U0_ap_start <= start_for_resize_1_9_480_640_600_1000_1_2_U0_empty_n;
    start_for_proc_Loop_VITIS_LOOP_132_3_proc7_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_proc_Loop_loop_read_proc6_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_proc_Loop_loop_write_proc8_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_resize_1_9_480_640_600_1000_1_2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_din <= (0=>ap_const_logic_1, others=>'-');
    warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_continue <= ap_const_logic_1;
    warpTransform_100_50_0_true_7_600_1000_1_false_U0_ap_start <= start_for_warpTransform_100_50_0_true_7_600_1000_1_false_U0_empty_n;
end behav;
