-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_s is
port (
    tmp_mat_46_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_mat_46_empty_n : IN STD_LOGIC;
    tmp_mat_46_read : OUT STD_LOGIC;
    out_mat_47_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_mat_47_full_n : IN STD_LOGIC;
    out_mat_47_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_s is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_start : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_done : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_continue : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_idle : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_tmp_mat_46_read : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_in_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_in_stream_write : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_start : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_idle : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_R_loc_channel : STD_LOGIC;
    signal R_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_R_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_R_loc_channel : STD_LOGIC;
    signal ap_channel_done_R_1_loc_channel : STD_LOGIC;
    signal R_1_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_R_1_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_R_1_loc_channel : STD_LOGIC;
    signal ap_channel_done_R_2_loc_channel : STD_LOGIC;
    signal R_2_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_R_2_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_R_2_loc_channel : STD_LOGIC;
    signal ap_channel_done_R_3_loc_channel : STD_LOGIC;
    signal R_3_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_R_3_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_R_3_loc_channel : STD_LOGIC;
    signal ap_channel_done_R_4_loc_channel : STD_LOGIC;
    signal R_4_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_R_4_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_R_4_loc_channel : STD_LOGIC;
    signal ap_channel_done_R_5_loc_channel : STD_LOGIC;
    signal R_5_loc_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_R_5_loc_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_R_5_loc_channel : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_start : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_done : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_continue : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_idle : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_start_out : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_start_write : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_in_stream_read : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_out_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_out_stream_write : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_start : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_done : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_continue : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_idle : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_ready : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_stream_read : STD_LOGIC;
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_mat_47_din : STD_LOGIC_VECTOR (31 downto 0);
    signal warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_mat_47_write : STD_LOGIC;
    signal in_stream_full_n : STD_LOGIC;
    signal in_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_empty_n : STD_LOGIC;
    signal R_5_loc_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal R_5_loc_channel_empty_n : STD_LOGIC;
    signal R_4_loc_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal R_4_loc_channel_empty_n : STD_LOGIC;
    signal R_3_loc_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal R_3_loc_channel_empty_n : STD_LOGIC;
    signal R_2_loc_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal R_2_loc_channel_empty_n : STD_LOGIC;
    signal R_1_loc_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal R_1_loc_channel_empty_n : STD_LOGIC;
    signal R_loc_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal R_loc_channel_empty_n : STD_LOGIC;
    signal out_stream_full_n : STD_LOGIC;
    signal out_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready : STD_LOGIC;
    signal start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_full_n : STD_LOGIC;
    signal start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        tmp_mat_46_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_mat_46_empty_n : IN STD_LOGIC;
        tmp_mat_46_read : OUT STD_LOGIC;
        in_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_stream_full_n : IN STD_LOGIC;
        in_stream_write : OUT STD_LOGIC );
    end component;


    component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_empty_n : IN STD_LOGIC;
        in_stream_read : OUT STD_LOGIC;
        out_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_full_n : IN STD_LOGIC;
        out_stream_write : OUT STD_LOGIC;
        p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_empty_n : IN STD_LOGIC;
        out_stream_read : OUT STD_LOGIC;
        out_mat_47_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_mat_47_full_n : IN STD_LOGIC;
        out_mat_47_write : OUT STD_LOGIC );
    end component;


    component rt_imp_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rt_imp_start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_bRq IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0 : component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_start,
        ap_done => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_done,
        ap_continue => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_continue,
        ap_idle => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_idle,
        ap_ready => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready,
        tmp_mat_46_dout => tmp_mat_46_dout,
        tmp_mat_46_empty_n => tmp_mat_46_empty_n,
        tmp_mat_46_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_tmp_mat_46_read,
        in_stream_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_in_stream_din,
        in_stream_full_n => in_stream_full_n,
        in_stream_write => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_in_stream_write);

    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0 : component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_start,
        ap_done => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done,
        ap_continue => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue,
        ap_idle => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_idle,
        ap_ready => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready,
        ap_return_0 => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_0,
        ap_return_1 => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_1,
        ap_return_2 => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_2,
        ap_return_3 => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_3,
        ap_return_4 => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_4,
        ap_return_5 => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_5);

    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0 : component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_start,
        start_full_n => start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_full_n,
        ap_done => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_done,
        ap_continue => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_continue,
        ap_idle => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_idle,
        ap_ready => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready,
        start_out => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_start_out,
        start_write => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_start_write,
        p_read => R_3_loc_channel_dout,
        p_read1 => R_5_loc_channel_dout,
        p_read2 => R_loc_channel_dout,
        p_read3 => R_2_loc_channel_dout,
        in_stream_dout => in_stream_dout,
        in_stream_empty_n => in_stream_empty_n,
        in_stream_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_in_stream_read,
        out_stream_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_out_stream_din,
        out_stream_full_n => out_stream_full_n,
        out_stream_write => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_out_stream_write,
        p_read4 => R_4_loc_channel_dout,
        p_read5 => R_1_loc_channel_dout);

    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0 : component rt_imp_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_start,
        ap_done => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_done,
        ap_continue => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_continue,
        ap_idle => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_idle,
        ap_ready => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_ready,
        out_stream_dout => out_stream_dout,
        out_stream_empty_n => out_stream_empty_n,
        out_stream_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_stream_read,
        out_mat_47_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_mat_47_din,
        out_mat_47_full_n => out_mat_47_full_n,
        out_mat_47_write => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_mat_47_write);

    in_stream_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_in_stream_din,
        if_full_n => in_stream_full_n,
        if_write => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_in_stream_write,
        if_dout => in_stream_dout,
        if_empty_n => in_stream_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_in_stream_read);

    R_5_loc_channel_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_0,
        if_full_n => R_5_loc_channel_full_n,
        if_write => ap_channel_done_R_5_loc_channel,
        if_dout => R_5_loc_channel_dout,
        if_empty_n => R_5_loc_channel_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready);

    R_4_loc_channel_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_1,
        if_full_n => R_4_loc_channel_full_n,
        if_write => ap_channel_done_R_4_loc_channel,
        if_dout => R_4_loc_channel_dout,
        if_empty_n => R_4_loc_channel_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready);

    R_3_loc_channel_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_2,
        if_full_n => R_3_loc_channel_full_n,
        if_write => ap_channel_done_R_3_loc_channel,
        if_dout => R_3_loc_channel_dout,
        if_empty_n => R_3_loc_channel_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready);

    R_2_loc_channel_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_3,
        if_full_n => R_2_loc_channel_full_n,
        if_write => ap_channel_done_R_2_loc_channel,
        if_dout => R_2_loc_channel_dout,
        if_empty_n => R_2_loc_channel_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready);

    R_1_loc_channel_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_4,
        if_full_n => R_1_loc_channel_full_n,
        if_write => ap_channel_done_R_1_loc_channel,
        if_dout => R_1_loc_channel_dout,
        if_empty_n => R_1_loc_channel_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready);

    R_loc_channel_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_return_5,
        if_full_n => R_loc_channel_full_n,
        if_write => ap_channel_done_R_loc_channel,
        if_dout => R_loc_channel_dout,
        if_empty_n => R_loc_channel_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_ready);

    out_stream_U : component rt_imp_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_out_stream_din,
        if_full_n => out_stream_full_n,
        if_write => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_out_stream_write,
        if_dout => out_stream_dout,
        if_empty_n => out_stream_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_stream_read);

    start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_bRq_U : component rt_imp_start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_bRq
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_din,
        if_full_n => start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_full_n,
        if_write => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_start_write,
        if_dout => start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_dout,
        if_empty_n => start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_empty_n,
        if_read => warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_ready);





    ap_sync_reg_channel_write_R_1_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_R_1_loc_channel <= ap_const_logic_0;
            else
                if (((warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_R_1_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_R_1_loc_channel <= ap_sync_channel_write_R_1_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_R_2_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_R_2_loc_channel <= ap_const_logic_0;
            else
                if (((warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_R_2_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_R_2_loc_channel <= ap_sync_channel_write_R_2_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_R_3_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_R_3_loc_channel <= ap_const_logic_0;
            else
                if (((warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_R_3_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_R_3_loc_channel <= ap_sync_channel_write_R_3_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_R_4_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_R_4_loc_channel <= ap_const_logic_0;
            else
                if (((warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_R_4_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_R_4_loc_channel <= ap_sync_channel_write_R_4_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_R_5_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_R_5_loc_channel <= ap_const_logic_0;
            else
                if (((warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_R_5_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_R_5_loc_channel <= ap_sync_channel_write_R_5_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_R_loc_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_R_loc_channel <= ap_const_logic_0;
            else
                if (((warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_R_loc_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_R_loc_channel <= ap_sync_channel_write_R_loc_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready <= ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready <= ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_R_1_loc_channel <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and (ap_sync_reg_channel_write_R_1_loc_channel xor ap_const_logic_1));
    ap_channel_done_R_2_loc_channel <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and (ap_sync_reg_channel_write_R_2_loc_channel xor ap_const_logic_1));
    ap_channel_done_R_3_loc_channel <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and (ap_sync_reg_channel_write_R_3_loc_channel xor ap_const_logic_1));
    ap_channel_done_R_4_loc_channel <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and (ap_sync_reg_channel_write_R_4_loc_channel xor ap_const_logic_1));
    ap_channel_done_R_5_loc_channel <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and (ap_sync_reg_channel_write_R_5_loc_channel xor ap_const_logic_1));
    ap_channel_done_R_loc_channel <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_done and (ap_sync_reg_channel_write_R_loc_channel xor ap_const_logic_1));
    ap_done <= warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_done;
    ap_idle <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_idle and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_idle and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_idle and warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_idle and (ap_const_logic_1 xor R_loc_channel_empty_n) and (ap_const_logic_1 xor R_1_loc_channel_empty_n) and (ap_const_logic_1 xor R_2_loc_channel_empty_n) and (ap_const_logic_1 xor R_3_loc_channel_empty_n) and (ap_const_logic_1 xor R_4_loc_channel_empty_n) and (ap_const_logic_1 xor R_5_loc_channel_empty_n));
    ap_ready <= ap_sync_ready;
    ap_sync_channel_write_R_1_loc_channel <= ((ap_channel_done_R_1_loc_channel and R_1_loc_channel_full_n) or ap_sync_reg_channel_write_R_1_loc_channel);
    ap_sync_channel_write_R_2_loc_channel <= ((ap_channel_done_R_2_loc_channel and R_2_loc_channel_full_n) or ap_sync_reg_channel_write_R_2_loc_channel);
    ap_sync_channel_write_R_3_loc_channel <= ((ap_channel_done_R_3_loc_channel and R_3_loc_channel_full_n) or ap_sync_reg_channel_write_R_3_loc_channel);
    ap_sync_channel_write_R_4_loc_channel <= ((ap_channel_done_R_4_loc_channel and R_4_loc_channel_full_n) or ap_sync_reg_channel_write_R_4_loc_channel);
    ap_sync_channel_write_R_5_loc_channel <= ((ap_channel_done_R_5_loc_channel and R_5_loc_channel_full_n) or ap_sync_reg_channel_write_R_5_loc_channel);
    ap_sync_channel_write_R_loc_channel <= ((ap_channel_done_R_loc_channel and R_loc_channel_full_n) or ap_sync_reg_channel_write_R_loc_channel);
    ap_sync_ready <= (ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready and ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready);
    ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready or ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready);
    ap_sync_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready <= (warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready or ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready);
    out_mat_47_din <= warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_mat_47_din;
    out_mat_47_write <= warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_out_mat_47_write;
    start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_din <= (0=>ap_const_logic_1, others=>'-');
    tmp_mat_46_read <= warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_tmp_mat_46_read;
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_continue <= (ap_sync_channel_write_R_loc_channel and ap_sync_channel_write_R_5_loc_channel and ap_sync_channel_write_R_4_loc_channel and ap_sync_channel_write_R_3_loc_channel and ap_sync_channel_write_R_2_loc_channel and ap_sync_channel_write_R_1_loc_channel);
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_start <= ((ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_COPY_MAT1_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_continue <= ap_const_logic_1;
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_MAIN_ROWS_proc_U0_ap_start <= (R_loc_channel_empty_n and R_5_loc_channel_empty_n and R_4_loc_channel_empty_n and R_3_loc_channel_empty_n and R_2_loc_channel_empty_n and R_1_loc_channel_empty_n);
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_continue <= ap_const_logic_1;
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_start <= ((ap_sync_reg_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_769_1_proc3_U0_ap_ready xor ap_const_logic_1) and ap_start);
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_continue <= ap_continue;
    warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_ap_start <= start_for_warpTransformKrnl_100_50_0_true_7_600_1000_1_false_Loop_VITIS_LOOP_786_3_proc4_U0_empty_n;
end behav;
